language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '8.11'
before_script:
- npm install -g codecov
- npm install
script:
- npm run test:prod && npm run build
deploy:
  provider: npm
  on:
    tags: true
  skip_cleanup: true
  email: lostintime.dev@gmail.com
  api_key:
    secure: JPjq2I6d7f05yoZ3c6eyGHoCQacM404pMAT7woOR8V7AClmrz7InbEuAqEKuO173ukt8J4RVcSiST76TkMd0KX1rtvraT4xSRTyYKjX1+2HzlpUC7+NOJhDIcmS6gAu8nJ11129m6YNuz27h3wR2WlrYX5ouhWayyU76AsLWpo0hmYccFcsa7Fsij/joPRd0NIRtBEi6ZqLq/M1SM2FOK72AgZ10Ud4mfoI8qLv1actTrLKwunS+x2CkRSWzGk4CqpmMk1zkfdyv2uHhEyQ59TptuVUJOHOzBxlS1GDk5WlQ1tmO6EtReWyi99zZC5/BZt5ztoRu5roQU6+TeXR3vSY3h1kAfQR9H1JpokhHB7pblRiWvM0y2s5uQvosAbL2ynsvnPMvCu7wdXGA6Rz5pJ4Sh15P3F8x+8vukkqBU616THsSGSa9rUlA6GiBQ2uIbzVDDtKX1V3g8EIMO5oXVTxMN/+KmHv2ajTYKFrcRjzBqzc2amdzeofzT0XwzTCMhjMmffalnet3S4Dr5zHRev5ijE33SbtN+IMZnyYBP2zxZllo1OEQyHyxF9eBP8+USfniRNVfbdff35iYaBpQ0xpnFE+V0tMVM4rAMuZdnFuKHxz+2z0upjdS7otZIVT3YW0e5nVxpVb8UEvxiiAgv05kGevCv/+8z8N2blFJMFs=
after_success:
- codecov
